"""initial

Revision ID: 18acf22193ba
Revises:
Create Date: 2026-07-30 14:53:54.525353

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "18acf22193ba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
